### ISSUE TITLE
1 - Introduction into Artificial Intelligence_protected.pdf | Slide 43 | Not working link

### ISSUE THREAD

**Issue by JonasWinter** [dominikjung42/AIAlgorithmsAndApplications#1]
>Rogerdudler Git Tutorial (↗ https://rogerdudler.github.io) gives an exzellent introduction for getting started with git and no deep shit ;)
>
>_Chapter 1, slide 43_

Unfortunately the link is not working.
Correct link: https://rogerdudler.github.io/git-guide/

**Comment by dominikjung42** [comment]
Hey Jonas, thanks for your hint. I updated the link in the current version of the slides. With the next commit it should be fine...

**Comment by denisden77** [comment]
What is password to open that file?
